name: Test

on:
  push:
    branches:
      - '**'
      - '!master'
  pull_request:

jobs:
  aqua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.local/share/aquaproj-aqua
          key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('aqua.yaml')}}
          restore-keys: |
            v1-aqua-installer-${{runner.os}}-${{runner.arch}}-
      - uses: aquaproj/aqua-installer@v3.0.0
        with:
          aqua_version: v2.27.1
          aqua_opts: "-a"
